### ISSUE TITLE
Form removal 

### ISSUE THREAD

**Issue by kpjmcg** [fredericjs/surfalize#11]
Form removal is the only major operation which appears to be missing from the library. Is it possible to add this feature? 

Form removal is done in the simplest case by polynomial regression with degree 3. Adding this feature, with a choice of degree, would require a more flexible approach to the explicit linear model used for leveling in the current library. Sklearn has this capability with its [PolynomialFeatures](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.PolynomialFeatures.html) function and [LinearRegression](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html#sklearn.linear_model.LinearRegression) models. Just requires a bit of annoying matrix reshaping to return the predictions in the original shape. 

I was also working on my own surface analysis library [Rough](https://kpjmcg.github.io/rough/) and you can see my basic implementation of form removal. 

[Surfile](https://github.com/andeledea/surfile/blob/708e14b4c372ae6539becb494608ce034956ec94/surfile/geometry.py#L41) also has a pure numpy implementation of form removal.

**Comment by fredericjs** [comment]
Hi, it's certainly possible, I'm just lacking the time right now to do it. Maybe you want to propose an implementation?
