### ISSUE TITLE
Request for the development of the Std(Texture Direction) metric.

### ISSUE THREAD

**Issue by singhyun90** [fredericjs/surfalize#12]
Hello.
Could you possibly help develop the Std(Texture Direction) metric for Surface Roughness? plz.
I've searched everywhere, and it seems that the Surfalize library is the best option, so I'm asking for your assistance.

**Comment by fredericjs** [comment]
Hi, I've looked into it but haven't reached an implementation that gives me the same results as MountainsMap, that's why I have put it on hold. Maybe someone with more expertise on the topic can contribute the code.

**Comment by singhyun90** [comment]
Thank you so much for your response.
