### ISSUE TITLE
Problems with importin the module.

### ISSUE THREAD

**Issue by CHILLQQ** [fredericjs/surfalize#13]
Hello,

I am struggling with import of your package.
First, I tried doing it with a python 3.7 environment, but you code isn't compatible with anything below 3.8. For example, you use walrus operator in your code (:=) which is only available from python 3.8. Just wanted to let you know about it.
I also tried to install the package with python 3.8 environment, but failed to import the module again.
I can share the first error as an example:
```
 File "/miniconda3/envs/surfaliz/lib/python3.8/site-packages/surfalize/file/sur.py", line 332
  with (open(filepath, 'rb') as filehandle):
                             ^
```
I can fix this one with be removing the outer parenthesis, but there are more errors after this one. So, I guess I want to ask is what is the exact python version you use to make this package work ?

**Comment by fredericjs** [comment]
Hi, I cannot reproduce these errors. Are you getting them directly on import? It works for me with Python >3.9, I haven't tested it with anything below that.

**Comment by CHILLQQ** [comment]
Thank you for quick response. It does work on python 3.9. Apparently, it isn't compatible with any earlier python version. Please consider adding this to the description.

**Comment by fredericjs** [comment]
Okay, will do. If you want, feel free to make it compatible and submit a pull request. However, if you look at major packages such as numpy, they dropped support for versions < 3.9 more than a year ago, so I'm not sure how useful it is to spent time on this.
