### ISSUE TITLE
API documentation deteriorated ?

### ISSUE THREAD

**Issue by taki-climb** [fredericjs/surfalize#16]
I'm excited to this library which is dedicated for surface morphological analysis. 
After using this for a while, I noticed that many part of API documentation (both stable and development versions) was vanished. 
Previously I could confirmed some description of Surface object, but now nothing is shown.
Currently, I manage to use this library by comparing source code and previous version documentation which is able to reconstruct below  procedure. But I realize that utility become worsen. Could you restore API documentations to previous version ?. 
Or API docs is underconstructions by dramatically change?

**Comment by taki-climb** [comment]
currently, I'm checking some method from testdoc version's documentations.
![スクリーンショット 2024-12-13 143243](https://github.com/user-attachments/assets/1af64fab-d0e1-42f9-a1b8-be97f5af8d73)

**Comment by fredericjs** [comment]
Hi, I also found the issue today, It should be fixed now. Can you confirm that it work for you again?

**Comment by taki-climb** [comment]
Thank you for replying and early improvement.
I also could confirm that API documentation was recovered.
