### ISSUE TITLE
Support for VMRL 2.0 Files

### ISSUE THREAD

**Issue by asuagar** [fredericjs/surfalize#9]
Hello,

I am trying to open a VMRL 2.0 file obtained using the Alicona3D software. Below is a sample of the file format. I have attempted to extract the first three columns and save them in an XYZ file. However, Surfalize performs a unique values check, resulting in an error (see the end of this message).

Could you please add support for this file format?  If that is not possible, any assistance with the conversion would be greatly appreciated. I can upload an example file if needed.

Best regards,
Andrés

VMRL 2.0 sample

```raw
GPoint3DVector { 3819808 n {
-3591.501419 978.121132 -20.305523 0 0 0
-3589.487500 978.123848 -20.727313 0 0 0
-3587.458451 978.130277 -21.725382 0 0 0
-3585.463047 978.128451 -21.441953 0 0 0
-3583.436760 978.134202 -22.334820 0 0 0
-3581.434317 978.134103 -22.319514 0 0 0
...
}
```

ERROR

```bash
File C:\py310\lib\site-packages\surfalize\file\xyz.py:19, in read_xyz(filepath, read_image_layers, encoding)
     17 ny = y.size
     18 if nx * ny != raw_data.shape[0]:
---> 19     raise CorruptedFileError('Number of datapoints does not match expected size.')
     20 step_x = (x.max() - x.min()) / (nx) * 10**6
     21 step_y = (y.max() - y.min()) / (ny) * 10**6

CorruptedFileError: Number of datapoints does not match expected size.
```

**Comment by fredericjs** [comment]
Hi,

could you upload a full sample file of this format?

**Comment by asuagar** [comment]
Hi,

[This link](https://drive.google.com/drive/folders/1bmU8e1HBthXC3v2D-jV_hMfepOH9LzV7?usp=sharing) contains a full sample and its corresponding image. Unfortunately, I did not save the "a3d" files.

Thanks and regards,
Andrés

**Comment by fredericjs** [comment]
Hi Andrés,

sorry for the late reply, I was on vacation. You file format seems very weird to me. Your datapoints do not lie on a regular grid. Why is that? What are we supposed to do with it? Should we interpolate them?

Best
Frederic

**Comment by asuagar** [comment]
Hello Frederic,

First of all, there's no need to apologize for your late reply. I'm grateful for your work.

I don’t have answers to all your questions. I believe the Alicona 3D solution is quite specific. It uses a subset of the VRML format to create a plain text version. There may be other software that can read it for visualization purpose.

I ran your code, and the xticks and yticks are correct. I consider the ticket closed. I could adapt your code to solve my problems.

Thank you very much for your help.

**Comment by asuagar** [comment]
Hello Frederic,

First of all, there's no need to apologize for your late reply. I'm grateful for your work.

I don’t have answers to all your questions. I believe the Alicona 3D solution is quite specific. It uses a subset of the VRML format to create a plain text version. There may be other software that can read it for visualization purpose.

I ran your code, and the xticks and yticks are correct. I consider the ticket closed. I could adapt your code to solve my problems.

Thank you very much for your help.
